name: "HCL AppScan CodeSweep Publish"
on:
  pull_request:
    types: [closed]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish issues to ASoC
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2
        with:
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          publish_on_merge: true
          application_id: 8828d53b-d9d8-4d1e-9f39-0058a5ab0ea2
          acceptssl: true
          status: failure
          service_url: ${{secrets.SERVICE_URL}}
    env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
